// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCmd(arg1, arg2) {
  return window['go']['sys']['Sys']['ExecuteCmd'](arg1, arg2);
}

export function ExecuteExternalCmdNoOutput(arg1) {
  return window['go']['sys']['Sys']['ExecuteExternalCmdNoOutput'](arg1);
}
