// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCmd(arg1:string,arg2:Array<string>):Promise<string>;

export function ExecuteExternalCmdNoOutput(arg1:string):Promise<boolean>;

export function Restart():Promise<void>;
