// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadNmap(arg1:string):Promise<boolean>;

export function InstallNmap():Promise<boolean>;

export function NmapExists():Promise<string>;
