// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallNmap(arg1) {
  return window['go']['nmap']['Nmap']['InstallNmap'](arg1);
}

export function NmapExists() {
  return window['go']['nmap']['Nmap']['NmapExists']();
}
