// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadNmap(arg1:string):Promise<string>;

export function InstallNmap():Promise<string>;

export function NmapExists():Promise<string>;
