// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadNmap(arg1) {
  return window['go']['nmap']['Nmap']['DownloadNmap'](arg1);
}

export function InstallNmap() {
  return window['go']['nmap']['Nmap']['InstallNmap']();
}

export function NmapExists() {
  return window['go']['nmap']['Nmap']['NmapExists']();
}
