// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1) {
  return window['go']['net']['Net']['DownloadFile'](arg1);
}

export function GetHostname() {
  return window['go']['net']['Net']['GetHostname']();
}

export function GetInternetIPAddress() {
  return window['go']['net']['Net']['GetInternetIPAddress']();
}

export function GetLocalIPAddress() {
  return window['go']['net']['Net']['GetLocalIPAddress']();
}

export function OpenEmail(arg1) {
  return window['go']['net']['Net']['OpenEmail'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['net']['Net']['OpenURL'](arg1);
}
