// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHostname() {
  return window['go']['net']['Net']['GetHostname']();
}

export function GetInternetIPAddress() {
  return window['go']['net']['Net']['GetInternetIPAddress']();
}

export function GetLocalIPAddress() {
  return window['go']['net']['Net']['GetLocalIPAddress']();
}
