// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1:string):Promise<string>;

export function GetHostname():Promise<string>;

export function GetInternetIPAddress():Promise<string>;

export function GetLocalIPAddress():Promise<string>;
